### ISSUE TITLE
v2.0.1 is missing in packagecloud stable and current 

### ISSUE THREAD

**Issue by rhass-r7** [chef/opscode-pushy-server#122]
I am not sure if this was intentionally pulled, an accidental tag/release version, or it never made it into packagecloud. Nevertheless, It looks like v2.0.1 of the server is missing from packagecloud `stable` and there does not appear to be any evidence of a 2.0.1 in `current` either.

@chef/engineering-services

**Comment by charlesjohnson** [comment]
Version 2.0.1 was never released out of `current`, although there was occasionally a problem with it being reaped by automation. 

Version 2.1 is now in `stable` and should resolve this issue.
