### ISSUE TITLE
Push jobs server returning 504 on all requests, no further info

### ISSUE THREAD

**Issue by rdjogo** [chef/opscode-pushy-server#193]
###  Push Jobs Server Version
Tried with 2.1.1 and 2.2.8, issue reproduced with both. Since `chef-server-ctl install opscode-push-jobs-server` didn't work out of the box, I reinstalled (several times) either simply via rpm or by passing the path to the rpm package `chef-server-ctl install opscode-push-jobs-server --path /tmp/opscode-push-jobs-server-2.2.8-1.el7.x86_64.rpm`

### Platform Details
Amazon Linux EC2 instance
```
  Operating System: Amazon Linux 2
       CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
            Kernel: Linux 4.14.88-88.76.amzn2.x86_64
      Architecture: x86-64
```

### Configuration
Standalone, Chef server version 12.19.26

### Scenario:
Any request, including running it from client, or web UI, or  knife utility, returns `504 Gateway Time-out` error, as well as most of the tests by running `opscode-push-jobs-server-ctl test`.

**Comment by rdjogo** [comment]
It was a security group issue. Even though the [docs](https://docs.chef.io/push_jobs.html) mention TCP ports 10000 and 10002, which I allowed, I found out that indeed the port 10003 is used in `/var/opt/opscode/nging/etc/addon.d/10-push_jobs_upstreams.conf` and confirmed with tcpdump.
Once I added 10003 to security group, everything worked out.
I guess a documentation PR is due.

**Comment by atrull** [comment]
I just got bitten by this too. 10003.
