### ISSUE TITLE
Chef Push jobs

### ISSUE THREAD

**Issue by AnamikaN** [chef/opscode-pushy-server#210]
I am trying to configure chef push jobs. Setup from my side is done. When I am trying knife node status nodename , it is showing unavailable. below are the logs from client node-

Retrieving configuration from https://chef/organizations/chef//pushy/config/node: ...
INFO: [node] Stopping command / server heartbeat receive thread and destroying sockets ...
INFO: [node] Resolved newchef-c-chefpjel-tem2unalflnp-1625445169.us-west-2.elb.amazonaws.com to '50.112.74.228' and 1 others
INFO: [node] Starting ZMQ version {:major=>4, :minor=>0, :patch=>5}
INFO: [node] Listening for server heartbeat at tcp://chef-c-chefpjel-tem2unalflnp-1625445169.us-west-2.elb.amazonaws.com:10000
INFO: [node] Connecting to command channel at tcp://chef-c-chefpjel-tem2unalflnp-1625445169.us-west-2.elb.amazonaws.com:10002
INFO: [node] Stopping heartbeat / offline detection thread ...
INFO: [node] Starting command / server heartbeat receive thread ...
INFO: [node] Considering server online, and starting to heartbeat
INFO: [node] Stopping reconfigure thread ...
INFO: [node] Starting heartbeat / offline detection thread on interval 10.0 ...
INFO: [node] Reconfigured client.
INFO: [node] Starting reconfigure thread.  Will reconfigure / reload keys after 3600 seconds, less up to splay 0.1.
INFO: [node] Forced GC; Stat count changed 1

What could be the issue?

**Comment by markan** [comment]
You'll probably get more eyes on this if you ask in the chef community slack channel, but a few quick thoughts
1) Check that the client and server clocks are close; too much (> 5 min) can cause problems
2) No timestamps on the log above; it would be helpful  know the timing of the various phases. Is there a lot of time elapsed between the messages 
```
INFO: [node] Starting command / server heartbeat receive thread ...
INFO: [node] Considering server online, and starting to heartbeat
INFO: [node] Stopping reconfigure thread ...
```

**Comment by AnamikaN** [comment]
My client node is in PST and server is in AWS, it shows UTC time.

Below are the times-

Client node - Fri Jan 24 12:32:23 PST 2020
server - Fri Jan 24 20:32:45 UTC 2020

**Comment by AnamikaN** [comment]
I figured out the issue. Port was not open on DC client node. I created an EC2 instance, and i tried push jobs from EC2 instance to chef server, which is also hosted on AWS. It worked as expected.
