### ISSUE TITLE
Execute a recipe on multiple nodes sequentially

### ISSUE THREAD

**Issue by AnamikaN** [chef/opscode-pushy-server#211]
Hi All.

Recently we have integrated push-jobs with chef to execute recipes from workstation itself. But here my question is how to execute single recipe on multiple nodes sequentially using push-jobs?.

Generally we can execute a recipe on a node with push-jobs using below command
knife job start ‘chef-client’ node-name (on one node).
but if i use like below command

knife job start ‘chef-client’ Node1 Node2 Node3 … the recipe executing on multiple nodes but it is executing parallelly on the multiple nodes.

Thanks in Advance…

**Comment by PrajaktaPurohit** [comment]
Hey @AnamikaN We can create a feature request for this and have product schedule it. As of today we do not support sequential execution in a single job. The only way to run sequential execution is to run multiple jobs with the Chef-Infra-Push-Jobs-Server.

**Comment by PrajaktaPurohit** [comment]
Status: to be prioritized

**Comment by AnamikaN** [comment]
@PrajaktaPurohit Thank you for your response.
